#ifndef ULTRASONIC_SENSOR_H
#define ULTRASONIC_SENSOR_H

#include "LPC407x_8x_177x_8x.h"
#include "LED.h"

#define ULTRASONIC_TIMER									LPC_TIM2
#define ULTRASONIC_ECHO_IOCON							LPC_IOCON->P0_4
#define ULTRASONIC_ECHO_GPIO							LPC_GPIO0
#define ULTRASONIC_ECHO_GPIO_PIN					4
#define ULTRASONIC_TRIGGER_IOCON					LPC_IOCON->P0_9
#define ULTRASONIC_TIMER_MR								MR3
#define ULTRASONIC_TIMER_CR								CR0
#define ULTRASONIC_TIMER_IRQN							TIMER2_IRQn
#define ULTRASONIC_TIMER_IRQHANDLER				TIMER2_IRQHandler
#define ULTRASONIC_ECHO_IOCON_FUNC				3
#define ULTRASONIC_TRIGGER_IOCON_FUNC			3
#define ULTRASONIC_TIMER_PCONP_BIT				22
#define ULTRASONIC_TIMER_MRI_BIT					9
#define ULTRASONIC_TIMER_MRR_BIT					10
#define ULTRASONIC_TIMER_EMC_BIT					10
#define ULTRASONIC_TIMER_CAPRE_BIT				0
#define ULTRASONIC_TIMER_CAPFE_BIT				1
#define ULTRASONIC_TIMER_CAPI_BIT					2
#define ULTRASONIC_TIMER_EM_BIT						3
#define ULTRASONIC_TIMER_MRINT_BIT				3
#define ULTRASONIC_TIMER_CRINT_BIT				4

extern uint32_t current_distance;
extern uint8_t distance_updated;

void ultrasonic_init(void);
void ULTRASONIC_TIMER_IRQHANDLER(void);

#endif
